[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
rootDirectory = "solana-rfp-app/backend"

[deploy.healthcheck]
path = "/health"
timeout = 300
