[build]
builder = "dockerfile"
dockerfilePath = "solana-rfp-app/backend/Dockerfile"
dockerContext = "solana-rfp-app/backend"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
timeout = 300
